# Generated by Django 3.0.9 on 2021-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('school', 'School'), ('work', 'Work'), ('self-improvement', 'Self-Improvement'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
