# Generated by Django 3.0.9 on 2021-04-19 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0002_auto_20210419_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('School', 'School'), ('Work', 'Work'), ('Self-improvement', 'Self-Improvement'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Housing', 'Housing'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=20)),
                ('projected', models.PositiveIntegerField()),
                ('actual', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
